import type { AssessmentData } from "../types.ts"
import { defaultAssessmentData } from "../storage.ts"

export type DemoApplicant = {
  id: string
  label: string
  notes: string
  answers: AssessmentData
}

function withBase(overrides: Partial<AssessmentData>): AssessmentData {
  const {
    languageScores: overrideLanguageScores,
    jobs: overrideJobs,
    additionalCredentials: overrideAdditionalCredentials,
    ...restOverrides
  } = overrides

  return {
    ...defaultAssessmentData,
    ...restOverrides,
    languageScores: {
      ...defaultAssessmentData.languageScores,
      ...(overrideLanguageScores ?? {}),
    },
    jobs: overrideJobs ?? defaultAssessmentData.jobs,
    additionalCredentials: overrideAdditionalCredentials ?? defaultAssessmentData.additionalCredentials,
  }
}

const pnpHighFitAnswers = withBase({
  firstName: "Maya",
  lastName: "Singh",
  dateOfBirth: "1993-04-12",
  citizenshipCountry: "India",
  currentProvinceTerritory: "British Columbia",
  intendedProvinceTerritory: "British Columbia",
  hasValidTemporaryStatus: "yes",
  temporaryStatusType: "work-permit-open",
  temporaryStatusExpiryDate: "2028-06-30",
  exactAge: 32,
  email: "maya.highfit@example.com",
  consentAcknowledged: true,

  primaryGoal: "pr",
  timeUrgency: "6-to-12",
  currentLocation: "inside-canada",
  geographicFlexibility: "prefer-specific",
  preferredProvince: "British Columbia",
  pnpTargetProvince: "British Columbia",
  deadlineTrigger: "no-hard-deadline",
  deadlineDate: "",
  openToPNP: "yes",

  currentStatus: "worker",
  statusExpiryDate: "2028-06-30",
  hasAppliedToExtendStatus: "no",
  refusalHistory: "no",
  mostRecentRefusalType: "",
  priorCanadaApplicationType: "",
  currentlyWorkingInCanada: "yes",
  currentJobProvinceTerritory: "British Columbia",
  sameEmployerForPermanentOffer: "yes",
  countryOfResidence: "Canada",
  nationality: "Indian",
  priorApplications: "no",

  currentJobTitle: "Data Engineer",
  countryOfWork: "Canada",
  industryCategory: "Technology",
  employmentGaps: "no",
  mostRecentJobStart: "2022-01",
  mostRecentJobEnd: "",
  mostRecentJobPresent: true,
  hoursPerWeekRange: "30plus",
  paidWorkStatus: "yes",
  employmentType: "employee",
  canObtainEmployerLetter: "yes",
  employerLetterChallenge: "",
  hasOverlappingPeriods: "no",
  hasCanadianJobOffer: "yes",
  jobOfferProvinceTerritory: "British Columbia",
  jobOfferTitle: "Data Engineer",
  jobOfferEmployerName: "Pacific Data Labs",
  jobOfferCity: "Vancouver",
  jobOfferFullTime: "yes",
  jobOfferPermanent: "yes",
  jobOfferCompensation: "105000",
  jobOfferCompensationType: "annual",
  jobOfferTenure: "2-plus-years",
  employerWillSupportPNP: "yes",
  occupationCategory: "it-software-data",
  occupationCategoryOtherRole: "",
  jobDuties:
    "Build and maintain production data pipelines, optimize ETL workflows, manage cloud data warehousing, and support analytics engineering teams.",
  foreignSkilledYears: "3",
  hasContinuous12MonthsSkilled: "yes",
  has12MonthsCanadaSkilled: "yes",
  canadianWorkAuthorizedAll: "yes",
  jobs: [
    {
      title: "Data Engineer",
      country: "Canada",
      yearsRange: "2022 – Present",
      startMonth: "2022-01",
      endMonth: "",
      present: true,
    },
  ],

  educationLevel: "bachelors",
  fieldOfStudy: "it-computer-science",
  educationCountry: "Canada",
  graduationYear: "2021",
  ecaStatus: "yes",
  canadaEducationStatus: "yes",
  educationCompletedInCanada: "yes",
  canadianEducationProvinceTerritory: "British Columbia",
  canadianEducationPublicInstitution: "yes",
  programLength: "2-years",
  hasMultipleCredentials: "no",
  additionalCredentials: [],
  ecaValid: "yes",

  languageTestStatus: "valid",
  languageTestPlan: "english-only",
  englishTestStatus: "completed",
  englishTestType: "ielts-general-training",
  englishPlannedTestDate: "",
  frenchTestStatus: "not-taken",
  frenchTestType: "",
  frenchPlannedTestDate: "",
  languageScores: {
    listening: "8.0",
    reading: "7.5",
    writing: "7.0",
    speaking: "7.5",
  },
  addScoresLater: false,
  ageRange: "30-34",
  canadianEducation: "yes",
  canadianWorkExperience: "yes",
  canadianWorkDuration: "2-plus-years",
  secondOfficialLanguageIntent: "no",

  maritalStatus: "single",
  dependents: 0,
  spouseAccompanying: "",
  spouseLocation: "",
  closeRelativeInCanada: "no",
  hasCloseRelativeInCanada: "no",
  relativeProvinceTerritory: "",
  closeRelativeRelationship: "",
  hasDependentsUnder18: "no",
  hasDependents18Plus: "no",
  sponsorshipTarget: "",
  sponsorStatus: "",
  partnerEducation: false,
  partnerLanguageScores: false,
  partnerWorkExperience: false,

  priorRefusals: "no",
  criminalCharges: "no",
  medicalIssues: "no",
  misrepresentation: "no",
  multipleCountries: "no",
  nonTraditionalEmployment: "no",
  missingDocuments: "no",
  statusExpiringSoon: "no",
  overstayHistory: "no",
  removalOrDeportationHistory: "no",
  hasActiveApplication: "no",
  employerLetterUnwilling: "no",
  workedWithoutAuthorizationInCanada: "no",
  refusedProvincialNomination: "no",
  isSkilledTrade: "no",
})

const pnpLowFitAnswers = withBase({
  firstName: "Noah",
  lastName: "Rivera",
  dateOfBirth: "1998-09-22",
  citizenshipCountry: "Brazil",
  currentProvinceTerritory: "Outside Canada",
  intendedProvinceTerritory: "Ontario",
  hasValidTemporaryStatus: "no",
  temporaryStatusType: "",
  temporaryStatusExpiryDate: "",
  exactAge: 27,
  email: "noah.lowfit@example.com",
  consentAcknowledged: true,

  primaryGoal: "pr",
  timeUrgency: "flexible",
  currentLocation: "outside-canada",
  geographicFlexibility: "yes-anywhere",
  preferredProvince: "",
  pnpTargetProvince: "",
  deadlineTrigger: "no-hard-deadline",
  deadlineDate: "",
  openToPNP: "yes",

  currentStatus: "other",
  statusExpiryDate: "",
  hasAppliedToExtendStatus: "",
  refusalHistory: "no",
  mostRecentRefusalType: "",
  priorCanadaApplicationType: "",
  currentlyWorkingInCanada: "no",
  currentJobProvinceTerritory: "",
  sameEmployerForPermanentOffer: "",
  countryOfResidence: "Brazil",
  nationality: "Brazilian",
  priorApplications: "unsure",

  currentJobTitle: "",
  countryOfWork: "Brazil",
  industryCategory: "",
  employmentGaps: "unsure",
  mostRecentJobStart: "2024-01",
  mostRecentJobEnd: "",
  mostRecentJobPresent: true,
  hoursPerWeekRange: "varies-not-sure",
  paidWorkStatus: "mix-not-sure",
  employmentType: "unsure",
  canObtainEmployerLetter: "unsure",
  employerLetterChallenge: "",
  hasOverlappingPeriods: "unsure",
  hasCanadianJobOffer: "unsure",
  jobOfferProvinceTerritory: "",
  jobOfferTitle: "",
  jobOfferEmployerName: "",
  jobOfferCity: "",
  jobOfferFullTime: "",
  jobOfferPermanent: "",
  jobOfferCompensation: "",
  jobOfferCompensationType: "",
  jobOfferTenure: "",
  employerWillSupportPNP: "",
  occupationCategory: "other",
  occupationCategoryOtherRole: "General support",
  jobDuties:
    "Performed mixed support tasks with changing responsibilities and no single documented job profile.",
  foreignSkilledYears: "0",
  hasContinuous12MonthsSkilled: "unsure",
  has12MonthsCanadaSkilled: "not_sure",
  canadianWorkAuthorizedAll: "not_sure",

  educationLevel: "high-school",
  fieldOfStudy: "other",
  educationCountry: "Brazil",
  graduationYear: "2016",
  ecaStatus: "not-sure",
  canadaEducationStatus: "no",
  educationCompletedInCanada: "no",
  canadianEducationProvinceTerritory: "",
  canadianEducationPublicInstitution: "",
  programLength: "",
  hasMultipleCredentials: "not-sure",
  additionalCredentials: [],
  ecaValid: "not-sure",

  languageTestStatus: "not_valid",
  languageTestPlan: "not-sure",
  englishTestStatus: "not-taken",
  englishTestType: "",
  englishPlannedTestDate: "",
  frenchTestStatus: "not-taken",
  frenchTestType: "",
  frenchPlannedTestDate: "",
  languageScores: {
    listening: "",
    reading: "",
    writing: "",
    speaking: "",
  },
  addScoresLater: true,
  ageRange: "25-29",
  canadianEducation: "not-sure",
  canadianWorkExperience: "unsure",
  canadianWorkDuration: "not-sure",
  secondOfficialLanguageIntent: "not-sure",

  maritalStatus: "single",
  dependents: 0,
  spouseAccompanying: "",
  spouseLocation: "",
  closeRelativeInCanada: "not-sure",
  hasCloseRelativeInCanada: "no",
  relativeProvinceTerritory: "",
  closeRelativeRelationship: "",
  hasDependentsUnder18: "not-sure",
  hasDependents18Plus: "not-sure",
  sponsorshipTarget: "",
  sponsorStatus: "",
  partnerEducation: false,
  partnerLanguageScores: false,
  partnerWorkExperience: false,

  priorRefusals: "unsure",
  criminalCharges: "no",
  medicalIssues: "no",
  misrepresentation: "no",
  multipleCountries: "unsure",
  nonTraditionalEmployment: "unsure",
  missingDocuments: "unsure",
  statusExpiringSoon: "na",
  overstayHistory: "no",
  removalOrDeportationHistory: "no",
  hasActiveApplication: "unsure",
  employerLetterUnwilling: "unsure",
  workedWithoutAuthorizationInCanada: "no",
  refusedProvincialNomination: "no",
  isSkilledTrade: "unsure",
})

export const demoApplicants: DemoApplicant[] = [
  {
    id: "pnp-high-fit",
    label: "PNP eligible (High fit)",
    notes:
      "PR-focused in-Canada profile with job offer, employer support, Canadian work/education, valid language results, and complete status details.",
    answers: pnpHighFitAnswers,
  },
  {
    id: "pnp-low-fit",
    label: "Low PNP eligibility (Low fit)",
    notes:
      "PR-focused outside-Canada profile with unclear/limited Canadian ties, language not ready, and documentation uncertainty.",
    answers: pnpLowFitAnswers,
  },
]
