import { defaultAssessmentData } from "./storage.ts"
import type { AssessmentData } from "./types.ts"

export type DemoProfileId = "ee-eligible" | "ee-needs-improvement" | "ee-ineligible"

export interface DemoProfile {
  id: DemoProfileId
  label: string
  description: string
  expectedOutcome: "eligible" | "needs_more_info" | "ineligible"
  data: AssessmentData
}

function buildProfile(overrides: Partial<AssessmentData>): AssessmentData {
  return {
    ...defaultAssessmentData,
    ...sharedBase,
    ...overrides,
    languageScores: {
      ...defaultAssessmentData.languageScores,
      ...sharedBase.languageScores,
      ...(overrides.languageScores ?? {}),
    },
    spouseLanguageScores: {
      ...defaultAssessmentData.spouseLanguageScores,
      ...sharedBase.spouseLanguageScores,
      ...(overrides.spouseLanguageScores ?? {}),
    },
  }
}

const sharedBase: Partial<AssessmentData> = {
  firstName: "Demo",
  middleName: "",
  lastName: "Candidate",
  dateOfBirth: "1992-06-15",
  citizenshipCountry: "India",
  currentProvinceTerritory: "Ontario",
  intendedProvinceTerritory: "Ontario",
  hasValidTemporaryStatus: "yes",
  temporaryStatusType: "work-permit-open",
  temporaryStatusExpiryDate: "2026-12-31",
  exactAge: 33,
  email: "demo@example.com",
  consentAcknowledged: true,
  primaryGoal: "pr",
  timeUrgency: "6-to-12",
  currentLocation: "inside-canada",
  geographicFlexibility: "yes-anywhere",
  preferredProvince: "",
  pnpTargetProvince: "",
  deadlineTrigger: "no-hard-deadline",
  deadlineDate: "",
  studyPermitHasLOA: "",
  workPermitHasJobOffer: "",
  sponsorshipRelation: "",
  openToPNP: "yes",
  currentStatus: "worker",
  statusExpiryDate: "2026-12-31",
  hasAppliedToExtendStatus: "no",
  refusalHistory: "no",
  mostRecentRefusalType: "",
  priorCanadaApplicationType: "",
  currentlyWorkingInCanada: "yes",
  currentJobProvinceTerritory: "Ontario",
  sameEmployerForPermanentOffer: "yes",
  countryOfResidence: "Canada",
  nationality: "Indian",
  priorApplications: "no",
  currentJobTitle: "Software Engineer",
  countryOfWork: "Canada",
  industryCategory: "Information Technology",
  employmentGaps: "no",
  mostRecentJobStart: "2023-01",
  mostRecentJobEnd: "",
  mostRecentJobPresent: true,
  hoursPerWeekRange: "30plus",
  paidWorkStatus: "yes",
  employmentType: "employee",
  canObtainEmployerLetter: "yes",
  employerLetterChallenge: "",
  hasOverlappingPeriods: "no",
  hasCanadianJobOffer: "yes",
  jobOfferProvinceTerritory: "Ontario",
  jobOfferTitle: "Software Engineer",
  jobOfferEmployerName: "Maple Tech Ltd.",
  jobOfferCity: "Toronto",
  jobOfferFullTime: "yes",
  jobOfferPermanent: "yes",
  jobOfferCompensation: "98000",
  jobOfferCompensationType: "annual",
  jobOfferTenure: "1-2-years",
  employerWillSupportPNP: "yes",
  jobOfferNonSeasonal: "yes",
  jobOfferSupportType: "lmia-exempt",
  jobOfferSupportBasis: "Employer-specific authorization",
  jobOfferIntendedDurationMonths: 24,
  jobOfferMeetsValidOfferDefinition: "yes",
  occupationCategory: "it-software-data",
  occupationCategoryOtherRole: "",
  jobDuties:
    "Design and maintain backend services, lead API architecture, document technical decisions, review code, and coordinate production incident resolution with product and operations teams.",
  foreignSkilledYears: "3",
  hasContinuous12MonthsSkilled: "yes",
  has12MonthsCanadaSkilled: "yes",
  canadianWorkAuthorizedAll: "yes",
  derivedCanadianSkilledYearsBand: "3",
  jobs: [],
  hasCanadianTradeCertificate: "no",
  tradeCertificateIssuingAuthority: "",
  tradeCertificateTrade: "",
  tradeCertificateIssueDate: "",
  educationLevel: "masters",
  fieldOfStudy: "it-computer-science",
  educationCountry: "India",
  graduationYear: "2016",
  ecaStatus: "yes",
  canadaEducationStatus: "no",
  educationCompletedInCanada: "no",
  canadianEducationProvinceTerritory: "",
  canadianEducationPublicInstitution: "",
  programLength: "2-years",
  hasMultipleCredentials: "no",
  additionalCredentials: [],
  ecaValid: "yes",
  languageTestStatus: "valid",
  languageTestPlannedDate: "",
  languageTestPlan: "english-only",
  englishTestStatus: "completed",
  englishTestType: "ielts-general-training",
  englishPlannedTestDate: "",
  frenchTestStatus: "not-taken",
  frenchTestType: "",
  frenchPlannedTestDate: "",
  languageScores: {
    listening: "8.5",
    reading: "7.5",
    writing: "7.0",
    speaking: "7.5",
  },
  addScoresLater: false,
  ageRange: "30-34",
  canadianEducation: "no",
  canadianWorkExperience: "yes",
  canadianWorkDuration: "2-plus-years",
  secondOfficialLanguageIntent: "no",
  maritalStatus: "single",
  dependents: 0,
  spouseAccompanying: "",
  spouseLocation: "",
  closeRelativeInCanada: "no",
  hasCloseRelativeInCanada: "no",
  relativeProvinceTerritory: "",
  closeRelativeRelationship: "",
  hasDependentsUnder18: "no",
  hasDependents18Plus: "no",
  sponsorshipTarget: "",
  sponsorStatus: "",
  partnerEducation: false,
  partnerLanguageScores: false,
  partnerWorkExperience: false,
  spouseEducationLevel: "",
  spouseForeignEducationHasEca: "",
  spouseEcaEquivalency: "",
  spouseEcaIssueDate: "",
  spouseLanguageTestType: "",
  spouseLanguageTestDate: "",
  spouseLanguageTestStream: "",
  spouseCanadianWorkMonths: null,
  spouseCanadianWorkStartDate: "",
  spouseCanadianWorkEndDate: "",
  hasEligibleSiblingInCanada: "no",
  siblingRelationshipType: "",
  siblingProvinceTerritory: "",
  siblingStatus: "",
  siblingAge18OrOlder: "",
  siblingLivesInCanada: "",
  fundsFamilySize: 1,
  settlementFundsCad: 22000,
  fundsExemptByValidJobOffer: "yes",
  priorRefusals: "no",
  criminalCharges: "no",
  medicalIssues: "no",
  misrepresentation: "no",
  multipleCountries: "no",
  nonTraditionalEmployment: "no",
  missingDocuments: "no",
  statusExpiringSoon: "no",
  overstayHistory: "no",
  removalOrDeportationHistory: "no",
  hasActiveApplication: "no",
  employerLetterUnwilling: "no",
  workedWithoutAuthorizationInCanada: "no",
  refusedProvincialNomination: "no",
  isSkilledTrade: "no",
}

const expressEntryEligibleProfile = buildProfile({
  firstName: "Arjun",
  lastName: "Sharma",
  workRoles: [
    {
      id: "eligible-canada-role",
      noc2021Code: "21231",
      teer: "1",
      title: "Software Engineer",
      employerName: "Maple Tech Ltd.",
      country: "Canada",
      province: "Ontario",
      city: "Toronto",
      startDate: "2023-01-01",
      endDate: "",
      present: true,
      hoursPerWeek: 40,
      hoursVaried: false,
      paid: true,
      employmentType: "employee",
      isSkilledTradeRole: false,
      wasAuthorizedInCanada: "yes",
      authorizationType: "work-permit-open",
      authorizationValidFrom: "2022-12-01",
      authorizationValidTo: "2026-12-31",
      wasFullTimeStudent: "no",
      physicallyInCanada: "yes",
      hasOverlapWithOtherRoles: "no",
    },
    {
      id: "eligible-foreign-role",
      noc2021Code: "21232",
      teer: "1",
      title: "Developer",
      employerName: "Delta Systems",
      country: "India",
      province: "",
      city: "Bengaluru",
      startDate: "2019-01-01",
      endDate: "2022-12-01",
      present: false,
      hoursPerWeek: 40,
      hoursVaried: false,
      paid: true,
      employmentType: "employee",
      isSkilledTradeRole: false,
      wasAuthorizedInCanada: "",
      authorizationType: "",
      authorizationValidFrom: "",
      authorizationValidTo: "",
      wasFullTimeStudent: "",
      physicallyInCanada: "",
      hasOverlapWithOtherRoles: "no",
    },
  ],
  educationCredentials: [
    {
      id: "eligible-edu-1",
      level: "masters",
      country: "India",
      isCanadianCredential: "no",
      issueDate: "2016-06-15",
      institutionName: "Delhi Institute of Technology",
      programLengthMonths: 24,
      studyLoad: "full-time",
      startDate: "2014-08-01",
      endDate: "2016-05-31",
      physicallyInCanada: "no",
      distanceLearningPercent: 0,
      ecaIssuer: "wes",
      ecaOtherIssuer: "",
      ecaReferenceNumber: "WES-EE-1001",
      ecaIssueDate: "2024-07-01",
      ecaEquivalency: "masters",
    },
  ],
  languageTests: [
    {
      id: "eligible-lang-1",
      isPrimary: true,
      testType: "ielts-general-training",
      stream: "general",
      testDate: "2025-11-01",
      registrationNumber: "TRF-EE-1001",
      scores: {
        listening: "8.5",
        reading: "7.5",
        writing: "7.0",
        speaking: "7.5",
      },
    },
  ],
  maritalStatus: "married",
  dependents: 1,
  spouseAccompanying: "yes-accompanying",
  spouseLocation: "in-canada",
  spouseEducationLevel: "bachelors",
  spouseForeignEducationHasEca: "yes",
  spouseEcaEquivalency: "bachelors",
  spouseEcaIssueDate: "2024-03-15",
  spouseLanguageTestType: "ielts-general-training",
  spouseLanguageTestDate: "2025-10-01",
  spouseLanguageTestStream: "general",
  spouseLanguageScores: {
    listening: "6.0",
    reading: "5.5",
    writing: "5.5",
    speaking: "6.0",
  },
  spouseCanadianWorkMonths: 8,
  spouseCanadianWorkStartDate: "2024-01-01",
  spouseCanadianWorkEndDate: "2024-08-31",
  hasEligibleSiblingInCanada: "yes",
  siblingRelationshipType: "applicant_sibling",
  siblingProvinceTerritory: "Ontario",
  siblingStatus: "citizen",
  siblingAge18OrOlder: "yes",
  siblingLivesInCanada: "yes",
  fundsFamilySize: 3,
  settlementFundsCad: 30000,
})

const expressEntryNeedsImprovementProfile = buildProfile({
  firstName: "Mina",
  lastName: "Patel",
  currentLocation: "outside-canada",
  hasValidTemporaryStatus: "no",
  temporaryStatusType: "",
  temporaryStatusExpiryDate: "",
  currentStatus: "other",
  statusExpiryDate: "2030-12-31",
  hasAppliedToExtendStatus: "",
  currentlyWorkingInCanada: "no",
  currentJobProvinceTerritory: "",
  sameEmployerForPermanentOffer: "",
  countryOfResidence: "India",
  currentProvinceTerritory: "Outside Canada",
  countryOfWork: "India",
  mostRecentJobStart: "2022-01",
  mostRecentJobEnd: "",
  mostRecentJobPresent: true,
  has12MonthsCanadaSkilled: "",
  canadianWorkAuthorizedAll: "",
  hasCanadianJobOffer: "no",
  jobOfferProvinceTerritory: "",
  jobOfferTitle: "",
  jobOfferEmployerName: "",
  jobOfferCity: "",
  jobOfferFullTime: "",
  jobOfferPermanent: "",
  jobOfferCompensation: "",
  jobOfferCompensationType: "",
  jobOfferTenure: "",
  employerWillSupportPNP: "",
  jobOfferNonSeasonal: "",
  jobOfferSupportType: "",
  jobOfferSupportBasis: "",
  jobOfferIntendedDurationMonths: null,
  jobOfferMeetsValidOfferDefinition: "",
  workRoles: [
    {
      id: "improve-foreign-role",
      noc2021Code: "13100",
      teer: "3",
      title: "Administrative Officer",
      employerName: "Global Services Pvt Ltd",
      country: "India",
      province: "",
      city: "Pune",
      startDate: "2022-01-01",
      endDate: "",
      present: true,
      hoursPerWeek: 40,
      hoursVaried: false,
      paid: true,
      employmentType: "employee",
      isSkilledTradeRole: false,
      wasAuthorizedInCanada: "",
      authorizationType: "",
      authorizationValidFrom: "",
      authorizationValidTo: "",
      wasFullTimeStudent: "",
      physicallyInCanada: "",
      hasOverlapWithOtherRoles: "no",
    },
  ],
  educationLevel: "bachelors",
  educationCountry: "India",
  ecaStatus: "yes",
  ecaValid: "no",
  educationCredentials: [
    {
      id: "improve-edu-1",
      level: "bachelors",
      country: "India",
      isCanadianCredential: "no",
      issueDate: "2018-06-01",
      institutionName: "Mumbai University",
      programLengthMonths: 36,
      studyLoad: "full-time",
      startDate: "2015-06-01",
      endDate: "2018-05-31",
      physicallyInCanada: "no",
      distanceLearningPercent: 0,
      ecaIssuer: "wes",
      ecaOtherIssuer: "",
      ecaReferenceNumber: "WES-EE-2001",
      ecaIssueDate: "2018-04-01",
      ecaEquivalency: "bachelors",
    },
  ],
  languageTestStatus: "valid",
  languageTestPlan: "english-only",
  languageScores: {
    listening: "7.5",
    reading: "6.5",
    writing: "6.5",
    speaking: "6.5",
  },
  languageTests: [
    {
      id: "improve-lang-1",
      isPrimary: true,
      testType: "ielts-general-training",
      stream: "general",
      testDate: "2025-08-01",
      registrationNumber: "TRF-EE-2001",
      scores: {
        listening: "7.5",
        reading: "6.5",
        writing: "6.5",
        speaking: "6.5",
      },
    },
  ],
  maritalStatus: "single",
  dependents: 0,
  fundsFamilySize: 1,
  fundsExemptByValidJobOffer: "no",
  settlementFundsCad: 15000,
  missingDocuments: "yes",
  multipleCountries: "yes",
})

const expressEntryIneligibleProfile = buildProfile({
  firstName: "Rosa",
  lastName: "Diaz",
  currentLocation: "outside-canada",
  hasValidTemporaryStatus: "no",
  temporaryStatusType: "",
  temporaryStatusExpiryDate: "",
  currentStatus: "other",
  statusExpiryDate: "2030-12-31",
  hasAppliedToExtendStatus: "",
  currentlyWorkingInCanada: "no",
  currentJobProvinceTerritory: "",
  sameEmployerForPermanentOffer: "",
  countryOfResidence: "Philippines",
  nationality: "Filipino",
  currentProvinceTerritory: "Outside Canada",
  countryOfWork: "Philippines",
  mostRecentJobStart: "2022-01",
  mostRecentJobEnd: "",
  mostRecentJobPresent: true,
  foreignSkilledYears: "0",
  has12MonthsCanadaSkilled: "",
  canadianWorkAuthorizedAll: "",
  hasCanadianJobOffer: "no",
  jobOfferProvinceTerritory: "",
  jobOfferTitle: "",
  jobOfferEmployerName: "",
  jobOfferCity: "",
  jobOfferFullTime: "",
  jobOfferPermanent: "",
  jobOfferCompensation: "",
  jobOfferCompensationType: "",
  jobOfferTenure: "",
  employerWillSupportPNP: "",
  jobOfferNonSeasonal: "",
  jobOfferSupportType: "",
  jobOfferSupportBasis: "",
  jobOfferIntendedDurationMonths: null,
  jobOfferMeetsValidOfferDefinition: "",
  occupationCategory: "sales-marketing",
  workRoles: [
    {
      id: "ineligible-role-1",
      noc2021Code: "64100",
      teer: "4",
      title: "Retail Sales Associate",
      employerName: "City Retail",
      country: "Philippines",
      province: "",
      city: "Manila",
      startDate: "2022-01-01",
      endDate: "",
      present: true,
      hoursPerWeek: 40,
      hoursVaried: false,
      paid: true,
      employmentType: "employee",
      isSkilledTradeRole: false,
      wasAuthorizedInCanada: "",
      authorizationType: "",
      authorizationValidFrom: "",
      authorizationValidTo: "",
      wasFullTimeStudent: "",
      physicallyInCanada: "",
      hasOverlapWithOtherRoles: "no",
    },
  ],
  educationLevel: "bachelors",
  educationCountry: "Canada",
  ecaStatus: "no",
  ecaValid: "",
  educationCompletedInCanada: "yes",
  canadianEducationProvinceTerritory: "Ontario",
  canadianEducationPublicInstitution: "yes",
  educationCredentials: [
    {
      id: "ineligible-edu-1",
      level: "bachelors",
      country: "Canada",
      isCanadianCredential: "yes",
      issueDate: "2020-06-01",
      institutionName: "Toronto College",
      programLengthMonths: 24,
      studyLoad: "full-time",
      startDate: "2018-09-01",
      endDate: "2020-05-31",
      physicallyInCanada: "yes",
      distanceLearningPercent: 0,
      ecaIssuer: "",
      ecaOtherIssuer: "",
      ecaReferenceNumber: "",
      ecaIssueDate: "",
      ecaEquivalency: "",
    },
  ],
  languageTestStatus: "valid",
  languageTestPlan: "english-only",
  languageScores: {
    listening: "4.5",
    reading: "4.0",
    writing: "4.0",
    speaking: "4.5",
  },
  languageTests: [
    {
      id: "ineligible-lang-1",
      isPrimary: true,
      testType: "ielts-general-training",
      stream: "general",
      testDate: "2025-10-01",
      registrationNumber: "TRF-EE-3001",
      scores: {
        listening: "4.5",
        reading: "4.0",
        writing: "4.0",
        speaking: "4.5",
      },
    },
  ],
  maritalStatus: "single",
  dependents: 0,
  fundsFamilySize: 1,
  fundsExemptByValidJobOffer: "no",
  settlementFundsCad: 5000,
  priorRefusals: "yes",
  multipleCountries: "yes",
  nonTraditionalEmployment: "yes",
  isSkilledTrade: "no",
})

export const EXPRESS_ENTRY_DEMO_PROFILES: DemoProfile[] = [
  {
    id: "ee-eligible",
    label: "Demo Profile 1: Express Entry Eligible",
    description: "Strong skilled work, valid language, and complete education proof.",
    expectedOutcome: "eligible",
    data: expressEntryEligibleProfile,
  },
  {
    id: "ee-needs-improvement",
    label: "Demo Profile 2: Needs Improvement",
    description: "Promising profile with documentation gaps (expired/insufficient ECA evidence).",
    expectedOutcome: "needs_more_info",
    data: expressEntryNeedsImprovementProfile,
  },
  {
    id: "ee-ineligible",
    label: "Demo Profile 3: Not Eligible",
    description: "Current inputs do not meet minimum program thresholds.",
    expectedOutcome: "ineligible",
    data: expressEntryIneligibleProfile,
  },
]

export function cloneDemoProfileData(profileId: DemoProfileId): AssessmentData {
  const match = EXPRESS_ENTRY_DEMO_PROFILES.find((profile) => profile.id === profileId)
  if (!match) {
    return JSON.parse(JSON.stringify(defaultAssessmentData)) as AssessmentData
  }
  return JSON.parse(JSON.stringify(match.data)) as AssessmentData
}
